// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWm-kMn5t7dwWNn9AEyBwl2CxhSqNhvUQ',
    appId: '1:995400650846:web:abaa3e71e053604da7e4cf',
    messagingSenderId: '995400650846',
    projectId: 'flutter-carpp-block-2025',
    authDomain: 'flutter-carpp-block-2025.firebaseapp.com',
    storageBucket: 'flutter-carpp-block-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ12-YYaE_EvaHUXbiABBvXutfU9aOyGM',
    appId: '1:995400650846:android:479e8ff338e4ea3ea7e4cf',
    messagingSenderId: '995400650846',
    projectId: 'flutter-carpp-block-2025',
    storageBucket: 'flutter-carpp-block-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPrn0sqTJq9kmRFdrf7bEKwCNn0fI8aKE',
    appId: '1:995400650846:ios:419d88d9c20fd5b1a7e4cf',
    messagingSenderId: '995400650846',
    projectId: 'flutter-carpp-block-2025',
    storageBucket: 'flutter-carpp-block-2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterBlockFirebaseCarapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPrn0sqTJq9kmRFdrf7bEKwCNn0fI8aKE',
    appId: '1:995400650846:ios:419d88d9c20fd5b1a7e4cf',
    messagingSenderId: '995400650846',
    projectId: 'flutter-carpp-block-2025',
    storageBucket: 'flutter-carpp-block-2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterBlockFirebaseCarapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWm-kMn5t7dwWNn9AEyBwl2CxhSqNhvUQ',
    appId: '1:995400650846:web:966b54b18e852d84a7e4cf',
    messagingSenderId: '995400650846',
    projectId: 'flutter-carpp-block-2025',
    authDomain: 'flutter-carpp-block-2025.firebaseapp.com',
    storageBucket: 'flutter-carpp-block-2025.firebasestorage.app',
  );
}
